data=
{
	"COMP3D_COMMIT" : "InitPublic-44-g499a6512",
	"COMP3D_COPYRIGHT" : "Copyright 1992-2024 IGN France www.ign.fr",
	"COMP3D_LICENSE" : "Provided with absolutely no warranty, under GPLv3 license",
	"COMP3D_OPTIONS" : "QT RES ",
	"COMP3D_REPO" : "https://github.com/IGNF/Comp3D",
	"COMP3D_VERSION" : "COMP3D v5.24dev-PROJ 9.4.0-linux",
	"all_data_files" : 
	{
		"0" : "coord.cor",
		"1" : "obs.obs"
	},
	"all_forbidden_point_names" : null,
	"all_point_names" : 
	[
		"o1",
		"o2",
		"s1",
		"s2",
		"1",
		"2",
		"4",
		"5",
		"c2"
	],
	"all_uninitializable_point_names" : 
	[
		"3",
		"c1"
	],
	"computation" : 
	{
		"Monte_Carlo_done" : false,
		"all_parameters_names" : 
		[
			"o2_x",
			"o2_y",
			"o2_z",
			"c2_x",
			"c2_y",
			"c2_z",
			"c2_G0_1",
			"5_x",
			"5_y",
			"5_z",
			"4_x",
			"4_y",
			"4_z",
			"2_x",
			"2_y",
			"2_z",
			"o1_x",
			"o1_y",
			"o1_z",
			"s2_x",
			"s2_y",
			"s2_z",
			"s2_G0_1",
			"s1_x",
			"s1_y",
			"s1_z",
			"s1_G0_1",
			"1_x",
			"1_y",
			"1_z"
		],
		"all_sigma0" : 
		[
			2.9044468750220651,
			0.1142407715345453,
			0.11424064567712219
		],
		"chi2_test" : 
		{
			"DOF" : 10,
			"confidence" : 0.98999999999999999,
			"max" : 2.1537241460618897,
			"min" : 0.63008858180757066
		},
		"compensation_done" : true,
		"computation_duration" : "00:00:00.003967",
		"computation_start" : "2025-Dec-09 13:54:28.720707",
		"internal_constraints" : false,
		"internal_constraints_obs" : [],
		"interrupted" : false,
		"inverted_matrix" : false,
		"kernel" : null,
		"messages_computation" : "",
		"messages_read_config" : "",
		"messages_read_data" : "Reading COR...<br/>\nRead file coord.cor...<br/>\nReading OBS...<br/>\nRead file obs.obs...<br/>\nPoints setting...<br/>\n<font color=#FF8000>&nbsp;&nbsp;&nbsp;&nbsp;7 uninitialized points.</font><br/>\nRead data finished.<br/>\nInitialization finished with 2 uninitialized points.<br/>\n<font color=#FF8000>&nbsp;&nbsp;&nbsp;&nbsp;Removing point 3.</font><br/>\n<font color=#FF8000>&nbsp;&nbsp;&nbsp;&nbsp;Removing point c1.</font><br/>\nVertical deflection not used.<br/>\n",
		"messages_set_least_squares" : "",
		"nbr_active_obs" : 40,
		"nbr_all_obs" : 40,
		"nbr_iterations" : 2,
		"nbr_parameters" : 30,
		"projection" : 
		{
			"center_latitude" : 48.79999999999999,
			"earth_model_radius" : 6380935.2757568145,
			"geocent_def" : "+proj=geocent",
			"input_proj_EPSG" : -1,
			"input_proj_def" : "+proj=sterea +lat_0=48.8 +lon_0=0 +k_0=1 +x_0=0 +y_0=0",
			"input_proj_name" : "?",
			"is_georef" : false,
			"latlong_def" : "+proj=latlong",
			"local_center_stereo" : 
			[
				0.0,
				0.0,
				0.0
			],
			"local_scale" : 1.0,
			"stereo_def" : "+proj=sterea +lat_0=48.8 +lon_0=0 +k_0=1 +x_0=0 +y_0=0"
		},
		"rank_deficiency" : 0,
		"sigma_0_final" : 0.11424064567712219,
		"sigma_0_init" : 2.9044468750220651,
		"solver_name" : "N5Eigen14SimplicialLDLTINS_12SparseMatrixIdLi0EiEELi1ENS_11AMDOrderingIiEEEE",
		"unit_name" : "g",
		"use_vertical_deflection" : false
	},
	"config" : 
	{
		"center_latitude" : 48.799999999999997,
		"clean_outputs" : false,
		"compute_type" : 0,
		"convergence_criterion" : 0.001,
		"coord_cov_file" : "",
		"description" : "",
		"display_map" : true,
		"files_unit" : 1,
		"force_iterations" : 0,
		"internal_constraints" : false,
		"invert_matrix" : false,
		"lang" : "en",
		"local_center" : 
		[
			0.0,
			0.0,
			0.0
		],
		"max_iterations" : 100,
		"misc_metadata" : null,
		"name" : "intersect",
		"nb_digits" : 4,
		"proj_def" : "+proj=lcc +lat_1=49 +lat_2=44 +lat_0=46.5 +lon_0=3 +x_0=700000 +y_0=6600000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs  <>",
		"refraction" : 0.12,
		"root_COR_file" : "coord.cor",
		"root_OBS_file" : "obs.obs",
		"use_ellips_height" : true,
		"use_proj" : false
	},
	"config_file" : "/home/JMMuller/prog/comp3d_cpp/tests/data/init_cap/ex_ref.comp_test.comp",
	"other_stations" : null,
	"points" : 
	{
		"1" : 
		{
			"code" : 0,
			"code_name" : "3---",
			"comment" : "",
			"coord_compensated_cartesian" : 
			[
				150.00141382753014,
				-9.2024571863191795e-05,
				59.998212014385501
			],
			"coord_compensated_georef" : 
			[
				150.00000545488777,
				-9.2026196761744853e-05,
				59.999972522059224
			],
			"coord_read" : 
			[
				149.99664832605546,
				0.0021421486965184609,
				60.000693728731221
			],
			"dev_eta" : null,
			"dev_xi" : null,
			"dimension" : 3,
			"ellips" : null,
			"file_id" : -1,
			"nbr_active_obs" : 4,
			"number" : 4,
			"params" : 
			{
				"1_x" : 
				{
					"rank" : 27,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 150.0000054341651
				},
				"1_y" : 
				{
					"rank" : 28,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : -9.2026196749031336e-05
				},
				"1_z" : 
				{
					"rank" : 29,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 59.999972522059224
				}
			},
			"shift_from_read" : 
			[
				0.0033571288323059889,
				-0.0022341748932802057,
				-0.0007212066719972654
			],
			"sigmas_init" : 
			[
				0.0,
				0.0,
				0.0
			],
			"stations" : []
		},
		"2" : 
		{
			"code" : 0,
			"code_name" : "3---",
			"comment" : "",
			"coord_compensated_cartesian" : 
			[
				90.001799867845691,
				90.001808190371833,
				129.99885777728991
			],
			"coord_compensated_georef" : 
			[
				89.999968963621015,
				89.99997192974422,
				130.00012720916988
			],
			"coord_read" : 
			[
				90.003944774436889,
				90.00430214227147,
				129.9869943171409
			],
			"dev_eta" : null,
			"dev_xi" : null,
			"dimension" : 3,
			"ellips" : null,
			"file_id" : -1,
			"nbr_active_obs" : 4,
			"number" : 5,
			"params" : 
			{
				"2_x" : 
				{
					"rank" : 13,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 89.999968954668844
				},
				"2_y" : 
				{
					"rank" : 14,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 89.999971920792049
				},
				"2_z" : 
				{
					"rank" : 15,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 130.00012720916988
				}
			},
			"shift_from_read" : 
			[
				-0.003975810815873615,
				-0.0043302125272504099,
				0.013132892028977494
			],
			"sigmas_init" : 
			[
				0.0,
				0.0,
				0.0
			],
			"stations" : []
		},
		"4" : 
		{
			"code" : 0,
			"code_name" : "3---",
			"comment" : "",
			"coord_compensated_cartesian" : 
			[
				140.00233279671508,
				130.00224264805871,
				109.99719186032709
			],
			"coord_compensated_georef" : 
			[
				139.99992290993384,
				129.99999835064611,
				110.00005168337047
			],
			"coord_read" : 
			[
				140.00297971175894,
				130.00116368638083,
				110.0002964780394
			],
			"dev_eta" : null,
			"dev_xi" : null,
			"dimension" : 3,
			"ellips" : null,
			"file_id" : -1,
			"nbr_active_obs" : 4,
			"number" : 6,
			"params" : 
			{
				"4_x" : 
				{
					"rank" : 10,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 139.99992287855824
				},
				"4_y" : 
				{
					"rank" : 11,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 129.99999832151161
				},
				"4_z" : 
				{
					"rank" : 12,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 110.00005168337047
				}
			},
			"shift_from_read" : 
			[
				-0.0030568018250960449,
				-0.0011653357347256588,
				-0.00024479466893012614
			],
			"sigmas_init" : 
			[
				0.0,
				0.0,
				0.0
			],
			"stations" : []
		},
		"5" : 
		{
			"code" : 0,
			"code_name" : "3---",
			"comment" : "",
			"coord_compensated_cartesian" : 
			[
				160.00294710586016,
				220.0041507630639,
				119.99424491277408
			],
			"coord_compensated_georef" : 
			[
				159.99994260508518,
				220.00000749169661,
				120.00004615629528
			],
			"coord_read" : 
			[
				160.00388100668596,
				220.00250997849653,
				119.99888631964401
			],
			"dev_eta" : null,
			"dev_xi" : null,
			"dimension" : 3,
			"ellips" : null,
			"file_id" : -1,
			"nbr_active_obs" : 4,
			"number" : 7,
			"params" : 
			{
				"5_x" : 
				{
					"rank" : 7,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 159.99994253238717
				},
				"5_y" : 
				{
					"rank" : 8,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 220.0000073917368
				},
				"5_z" : 
				{
					"rank" : 9,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 120.00004615629528
				}
			},
			"shift_from_read" : 
			[
				-0.0039384016007772971,
				-0.0025024867999263734,
				0.0011598366512686198
			],
			"sigmas_init" : 
			[
				0.0,
				0.0,
				0.0
			],
			"stations" : []
		},
		"c2" : 
		{
			"code" : 0,
			"code_name" : "3---",
			"comment" : "",
			"coord_compensated_cartesian" : 
			[
				150.00234862947397,
				50.000784673578721,
				99.998253882437666
			],
			"coord_compensated_georef" : 
			[
				150.00000132435895,
				49.999999946891712,
				100.00021058660558
			],
			"coord_read" : 
			[
				150.00000000767503,
				49.999999986184882,
				100.00077750451392
			],
			"dev_eta" : null,
			"dev_xi" : null,
			"dimension" : 3,
			"ellips" : null,
			"file_id" : -1,
			"nbr_active_obs" : 8,
			"number" : 8,
			"params" : 
			{
				"c2_x" : 
				{
					"rank" : 3,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 150.00000130133381
				},
				"c2_y" : 
				{
					"rank" : 4,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 49.999999939216664
				},
				"c2_z" : 
				{
					"rank" : 5,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 100.00021058660558
				}
			},
			"shift_from_read" : 
			[
				1.316683921004369e-06,
				-3.9293169606935408e-08,
				-0.00056691790834406675
			],
			"sigmas_init" : 
			[
				0.0,
				0.0,
				0.0
			],
			"stations" : 
			[
				{
					"nbr_active_obs" : 4,
					"num" : 1,
					"observations" : 
					[
						{
							"active" : true,
							"active_read" : true,
							"code" : 7,
							"comment" : "",
							"computed_value" : -150.0000000000955,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "c2",
							"instrument_height" : 0.0,
							"line" : 36,
							"normalized_residual" : -1.1937681904426396e-07,
							"number" : 44,
							"obs_azim" : -2.3561676766970825,
							"obs_length" : 70.711786184037166,
							"obs_zen" : 1.570805024928609,
							"original_value" : -150.0,
							"rank" : 32,
							"residual" : -9.5501455235411195e-11,
							"sigma_abs" : 0.00080000000000000004,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.00080000000000000004,
							"target_height" : 0.0,
							"to" : "o1",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : 150.00000000009291,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "c2",
							"instrument_height" : 0.0,
							"line" : 38,
							"normalized_residual" : 1.1619626436280046e-07,
							"number" : 46,
							"obs_azim" : 2.356221303690567,
							"obs_length" : 70.711786171011852,
							"obs_zen" : 1.5708050118242058,
							"original_value" : 150.0,
							"rank" : 33,
							"residual" : 9.2957011490240372e-11,
							"sigma_abs" : 0.00080000000000000004,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.00080000000000000004,
							"target_height" : 0.0,
							"to" : "o2",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : -50.000000000385491,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "c2",
							"instrument_height" : 0.0,
							"line" : 40,
							"normalized_residual" : -4.8188937373818337e-07,
							"number" : 48,
							"obs_azim" : -0.78537134990674096,
							"obs_length" : 70.711790076653656,
							"obs_zen" : 1.5708033790429137,
							"original_value" : -50.0,
							"rank" : 34,
							"residual" : -3.8551149899054679e-10,
							"sigma_abs" : 0.00080000000000000004,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.00080000000000000004,
							"target_height" : 0.0,
							"to" : "s1",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : 50.000000000388248,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "c2",
							"instrument_height" : 0.0,
							"line" : 42,
							"normalized_residual" : 4.852819653984111e-07,
							"number" : 50,
							"obs_azim" : 0.78542497690030966,
							"obs_length" : 70.711782571818318,
							"obs_zen" : 1.5708033073102057,
							"original_value" : 50.0,
							"rank" : 35,
							"residual" : 3.8822557231872899e-10,
							"sigma_abs" : 0.00080000000000000004,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.00080000000000000004,
							"target_height" : 0.0,
							"to" : "s2",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						}
					],
					"params" : 
					{
						"c2_G0_1" : 
						{
							"rank" : 6,
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"value" : 2.681349676265558e-05
						}
					},
					"type" : "hz_unknown"
				},
				{
					"nbr_active_obs" : 4,
					"num" : 1,
					"observations" : 
					[
						{
							"active" : true,
							"active_read" : true,
							"code" : 6,
							"comment" : "",
							"computed_value" : 100.00055374039039,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "c2",
							"instrument_height" : 0.0,
							"line" : 37,
							"normalized_residual" : -0.14625960959586368,
							"number" : 45,
							"obs_azim" : -2.3561676766970825,
							"obs_length" : 70.711786184037166,
							"obs_zen" : 1.570805024928609,
							"original_value" : 100.00069999999999,
							"rank" : 36,
							"residual" : -0.00014625960959586368,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "o1",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 6,
							"comment" : "",
							"computed_value" : 100.00055290613818,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "c2",
							"instrument_height" : 0.0,
							"line" : 39,
							"normalized_residual" : -0.14709386180887529,
							"number" : 47,
							"obs_azim" : 2.356221303690567,
							"obs_length" : 70.711786171011852,
							"obs_zen" : 1.5708050118242058,
							"original_value" : 100.00069999999999,
							"rank" : 37,
							"residual" : -0.00014709386180887529,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "o2",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 6,
							"comment" : "",
							"computed_value" : 100.00044896005272,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "c2",
							"instrument_height" : 0.0,
							"line" : 41,
							"normalized_residual" : 0.14896005273470536,
							"number" : 49,
							"obs_azim" : -0.78537134990674096,
							"obs_length" : 70.711790076653656,
							"obs_zen" : 1.5708033790429137,
							"original_value" : 100.0003,
							"rank" : 38,
							"residual" : 0.00014896005273470537,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "s1",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 6,
							"comment" : "",
							"computed_value" : 100.0004443934067,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "c2",
							"instrument_height" : 0.0,
							"line" : 43,
							"normalized_residual" : 0.144393406711148,
							"number" : 51,
							"obs_azim" : 0.78542497690030966,
							"obs_length" : 70.711782571818318,
							"obs_zen" : 1.5708033073102057,
							"original_value" : 100.0003,
							"rank" : 39,
							"residual" : 0.00014439340671114801,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "s2",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						}
					],
					"params" : null,
					"type" : "simple"
				}
			]
		},
		"o1" : 
		{
			"code" : 1,
			"code_name" : "3xyz",
			"comment" : "",
			"coord_compensated_cartesian" : 
			[
				100.00156625005376,
				1.4817160831626097e-09,
				99.99915785637009
			],
			"coord_compensated_georef" : 
			[
				100.00000137496268,
				4.1536883824495692e-10,
				99.999940307381053
			],
			"coord_read" : 
			[
				100.0,
				0.0,
				100.0
			],
			"dev_eta" : null,
			"dev_xi" : null,
			"dimension" : 3,
			"ellips" : null,
			"file_id" : 0,
			"nbr_active_obs" : 7,
			"number" : 0,
			"params" : 
			{
				"o1_x" : 
				{
					"rank" : 16,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 100.00000136882265
				},
				"o1_y" : 
				{
					"rank" : 17,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 4.1536883821945319e-10
				},
				"o1_z" : 
				{
					"rank" : 18,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 99.999940307381053
				}
			},
			"shift_from_read" : 
			[
				1.3749626788239766e-06,
				4.1536883824495692e-10,
				-5.9692618947337905e-05
			],
			"sigmas_init" : 
			[
				0.001,
				0.001,
				0.001
			],
			"stations" : 
			[
				{
					"nbr_active_obs" : 3,
					"num" : 1,
					"observations" : 
					[
						{
							"active" : true,
							"active_read" : true,
							"code" : -1,
							"comment" : "",
							"computed_value" : 100.00000136882265,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "o1",
							"instrument_height" : 0.0,
							"line" : 1,
							"normalized_residual" : 0.0013749626930348313,
							"number" : 0,
							"obs_azim" : 1.787550483144608e-05,
							"obs_length" : 0.0,
							"obs_zen" : 0.0,
							"original_value" : 99.999999993859959,
							"rank" : 0,
							"residual" : 1.3749626930348313e-06,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "o1",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : -2,
							"comment" : "",
							"computed_value" : 4.1536883821945319e-10,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "o1",
							"instrument_height" : 0.0,
							"line" : 1,
							"normalized_residual" : 4.1536883821945317e-07,
							"number" : 1,
							"obs_azim" : 1.787550483144608e-05,
							"obs_length" : 0.0,
							"obs_zen" : 0.0,
							"original_value" : 0.0,
							"rank" : 1,
							"residual" : 4.1536883821945319e-10,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "o1",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : -3,
							"comment" : "",
							"computed_value" : 99.999940307810903,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "o1",
							"instrument_height" : 0.0,
							"line" : 1,
							"normalized_residual" : -0.05969218909740448,
							"number" : 2,
							"obs_azim" : 1.787550483144608e-05,
							"obs_length" : 0.0,
							"obs_zen" : 0.0,
							"original_value" : 100.0,
							"rank" : 2,
							"residual" : -5.969218909740448e-05,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "o1",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						}
					],
					"params" : null,
					"type" : "simple"
				}
			]
		},
		"o2" : 
		{
			"code" : 1,
			"code_name" : "3xyz",
			"comment" : "",
			"coord_compensated_cartesian" : 
			[
				200.0031309779647,
				4.0117811295203865e-09,
				99.996811423273272
			],
			"coord_compensated_georef" : 
			[
				200.00000126454609,
				4.1870727953570588e-10,
				99.999941234968901
			],
			"coord_read" : 
			[
				200.0,
				0.0,
				100.0
			],
			"dev_eta" : null,
			"dev_xi" : null,
			"dimension" : 3,
			"ellips" : null,
			"file_id" : 0,
			"nbr_active_obs" : 7,
			"number" : 1,
			"params" : 
			{
				"o2_x" : 
				{
					"rank" : 0,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 200.00000121542573
				},
				"o2_y" : 
				{
					"rank" : 1,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 4.1870727943287063e-10
				},
				"o2_z" : 
				{
					"rank" : 2,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 99.999941234968901
				}
			},
			"shift_from_read" : 
			[
				1.264546085621987e-06,
				4.1870727953570588e-10,
				-5.876503109902842e-05
			],
			"sigmas_init" : 
			[
				0.001,
				0.001,
				0.001
			],
			"stations" : 
			[
				{
					"nbr_active_obs" : 3,
					"num" : 1,
					"observations" : 
					[
						{
							"active" : true,
							"active_read" : true,
							"code" : -1,
							"comment" : "",
							"computed_value" : 200.00000121542573,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "o2",
							"instrument_height" : 0.0,
							"line" : 2,
							"normalized_residual" : 0.001264546085621987,
							"number" : 3,
							"obs_azim" : 3.5751009379110597e-05,
							"obs_length" : 0.0,
							"obs_zen" : 0.0,
							"original_value" : 199.99999995087964,
							"rank" : 3,
							"residual" : 1.264546085621987e-06,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "o2",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : -2,
							"comment" : "",
							"computed_value" : 4.1870727943287063e-10,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "o2",
							"instrument_height" : 0.0,
							"line" : 2,
							"normalized_residual" : 4.1870727943287063e-07,
							"number" : 4,
							"obs_azim" : 3.5751009379110597e-05,
							"obs_length" : 0.0,
							"obs_zen" : 0.0,
							"original_value" : 0.0,
							"rank" : 4,
							"residual" : 4.1870727943287063e-10,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "o2",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : -3,
							"comment" : "",
							"computed_value" : 99.999941235408187,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "o2",
							"instrument_height" : 0.0,
							"line" : 2,
							"normalized_residual" : -0.058764591813087463,
							"number" : 5,
							"obs_azim" : 3.5751009379110597e-05,
							"obs_length" : 0.0,
							"obs_zen" : 0.0,
							"original_value" : 100.0,
							"rank" : 5,
							"residual" : -5.8764591813087463e-05,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "o2",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						}
					],
					"params" : null,
					"type" : "simple"
				}
			]
		},
		"s1" : 
		{
			"code" : 1,
			"code_name" : "3xyz",
			"comment" : "",
			"coord_compensated_cartesian" : 
			[
				100.00156349605901,
				100.00157208741291,
				99.998489498312708
			],
			"coord_compensated_georef" : 
			[
				99.999998625411649,
				100.00000263909342,
				100.00005669283549
			],
			"coord_read" : 
			[
				100.0,
				100.0,
				100.0
			],
			"dev_eta" : null,
			"dev_xi" : null,
			"dimension" : 3,
			"ellips" : null,
			"file_id" : 0,
			"nbr_active_obs" : 15,
			"number" : 2,
			"params" : 
			{
				"s1_x" : 
				{
					"rank" : 23,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 99.999998613131567
				},
				"s1_y" : 
				{
					"rank" : 24,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 100.00000262681334
				},
				"s1_z" : 
				{
					"rank" : 25,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 100.00005669283549
				}
			},
			"shift_from_read" : 
			[
				-1.3745883506999235e-06,
				2.6390934237952024e-06,
				5.6692835485705473e-05
			],
			"sigmas_init" : 
			[
				0.001,
				0.001,
				0.001
			],
			"stations" : 
			[
				{
					"nbr_active_obs" : 8,
					"num" : 1,
					"observations" : 
					[
						{
							"active" : true,
							"active_read" : true,
							"code" : -1,
							"comment" : "",
							"computed_value" : 99.999998613131567,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "s1",
							"instrument_height" : 0.0,
							"line" : 3,
							"normalized_residual" : -0.0013745883506999235,
							"number" : 6,
							"obs_azim" : 1.7875946683577915e-05,
							"obs_length" : 0.0,
							"obs_zen" : 0.0,
							"original_value" : 99.999999987719917,
							"rank" : 6,
							"residual" : -1.3745883506999235e-06,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "s1",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : -2,
							"comment" : "",
							"computed_value" : 100.00000262681334,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "s1",
							"instrument_height" : 0.0,
							"line" : 3,
							"normalized_residual" : 0.0026390934237952024,
							"number" : 7,
							"obs_azim" : 1.7875946683577915e-05,
							"obs_length" : 0.0,
							"obs_zen" : 0.0,
							"original_value" : 99.999999987719917,
							"rank" : 7,
							"residual" : 2.6390934237952024e-06,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "s1",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : -3,
							"comment" : "",
							"computed_value" : 100.00005669239908,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "s1",
							"instrument_height" : 0.0,
							"line" : 3,
							"normalized_residual" : 0.056692399084568024,
							"number" : 8,
							"obs_azim" : 1.7875946683577915e-05,
							"obs_length" : 0.0,
							"obs_zen" : 0.0,
							"original_value" : 100.0,
							"rank" : 8,
							"residual" : 5.6692399084568024e-05,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "s1",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 6,
							"comment" : "",
							"computed_value" : 100.00051307475844,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "s1",
							"instrument_height" : 0.0,
							"line" : 2,
							"normalized_residual" : 0.11307475844597314,
							"number" : 13,
							"obs_azim" : 3.1416105018567659,
							"obs_length" : 100.0015697938402,
							"obs_zen" : 1.5708043861543561,
							"original_value" : 100.0004,
							"rank" : 9,
							"residual" : 0.00011307475844597315,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "o1",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 6,
							"comment" : "",
							"computed_value" : 121.87329774314517,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "s1",
							"instrument_height" : 0.0,
							"line" : 4,
							"normalized_residual" : -0.0022568548385897978,
							"number" : 15,
							"obs_azim" : 2.6779632443458672,
							"obs_length" : 118.74485160241663,
							"obs_zen" : 1.914381284293132,
							"original_value" : 121.8733,
							"rank" : 10,
							"residual" : -2.2568548385897977e-06,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "1",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 6,
							"comment" : "",
							"computed_value" : 28.044300799690962,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "s1",
							"instrument_height" : 0.0,
							"line" : 6,
							"normalized_residual" : 0.00079969096294196134,
							"number" : 17,
							"obs_azim" : -2.3561766667462329,
							"obs_length" : 33.166438569752451,
							"obs_zen" : 0.44051884683685749,
							"original_value" : 28.0443,
							"rank" : 11,
							"residual" : 7.9969096294196139e-07,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "2",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 6,
							"comment" : "",
							"computed_value" : 87.433819971086891,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "s1",
							"instrument_height" : 0.0,
							"line" : 10,
							"normalized_residual" : 0.019971086886285357,
							"number" : 21,
							"obs_azim" : 0.9273122538477172,
							"obs_length" : 50.990938994941878,
							"obs_zen" : 1.3734072324822957,
							"original_value" : 87.433800000000005,
							"rank" : 12,
							"residual" : 1.9971086886285356e-05,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "4",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 6,
							"comment" : "",
							"computed_value" : 90.579960062440463,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "s1",
							"instrument_height" : 0.0,
							"line" : 12,
							"normalized_residual" : -0.039937559522789434,
							"number" : 23,
							"obs_azim" : 0.463665095217282,
							"obs_length" : 135.64886507402639,
							"obs_zen" : 1.4228266854730993,
							"original_value" : 90.579999999999998,
							"rank" : 13,
							"residual" : -3.9937559522789436e-05,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "5",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						}
					],
					"params" : null,
					"type" : "simple"
				},
				{
					"nbr_active_obs" : 5,
					"num" : 1,
					"observations" : 
					[
						{
							"active" : true,
							"active_read" : true,
							"code" : 7,
							"comment" : "",
							"computed_value" : 200.0000013825198,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "s1",
							"instrument_height" : 0.0,
							"line" : 1,
							"normalized_residual" : 0.0017281497213596686,
							"number" : 12,
							"obs_azim" : 3.1416105018567659,
							"obs_length" : 100.0015697938402,
							"obs_zen" : 1.5708043861543561,
							"original_value" : 200.0,
							"rank" : 22,
							"residual" : 1.3825197770877352e-06,
							"sigma_abs" : 0.00080000000000000004,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.00080000000000000004,
							"target_height" : 0.0,
							"to" : "o1",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : 170.48330022897562,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "s1",
							"instrument_height" : 0.0,
							"line" : 3,
							"normalized_residual" : 0.00028621952936476024,
							"number" : 14,
							"obs_azim" : 2.6779632443458672,
							"obs_length" : 118.74485160241663,
							"obs_zen" : 1.914381284293132,
							"original_value" : 170.48330000000001,
							"rank" : 23,
							"residual" : 2.2897562349180822e-07,
							"sigma_abs" : 0.00080000000000000004,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.00080000000000000004,
							"target_height" : 0.0,
							"to" : "1",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : -150.00000019762527,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "s1",
							"instrument_height" : 0.0,
							"line" : 5,
							"normalized_residual" : -0.00024703156173948364,
							"number" : 16,
							"obs_azim" : -2.3561766667462329,
							"obs_length" : 33.166438569752451,
							"obs_zen" : 0.44051884683685749,
							"original_value" : -150.0,
							"rank" : 24,
							"residual" : -1.9762524939158696e-07,
							"sigma_abs" : 0.00080000000000000004,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.00080000000000000004,
							"target_height" : 0.0,
							"to" : "2",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : 59.033396722374313,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "s1",
							"instrument_height" : 0.0,
							"line" : 9,
							"normalized_residual" : -0.004097032078359172,
							"number" : 20,
							"obs_azim" : 0.9273122538477172,
							"obs_length" : 50.990938994941878,
							"obs_zen" : 1.3734072324822957,
							"original_value" : 59.0334,
							"rank" : 25,
							"residual" : -3.2776256626873379e-06,
							"sigma_abs" : 0.00080000000000000004,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.00080000000000000004,
							"target_height" : 0.0,
							"to" : "4",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : 29.516701863755955,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "s1",
							"instrument_height" : 0.0,
							"line" : 11,
							"normalized_residual" : 0.0023296949548061697,
							"number" : 22,
							"obs_azim" : 0.463665095217282,
							"obs_length" : 135.64886507402639,
							"obs_zen" : 1.4228266854730993,
							"original_value" : 29.5167,
							"rank" : 26,
							"residual" : 1.863755963844936e-06,
							"sigma_abs" : 0.00080000000000000004,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.00080000000000000004,
							"target_height" : 0.0,
							"to" : "5",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						}
					],
					"params" : 
					{
						"s1_G0_1" : 
						{
							"rank" : 26,
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"value" : 1.7826550402658904e-05
						}
					},
					"type" : "hz_unknown"
				}
			]
		},
		"s2" : 
		{
			"code" : 1,
			"code_name" : "3xyz",
			"comment" : "",
			"coord_compensated_cartesian" : 
			[
				200.00312843978705,
				100.00156678941653,
				99.996147210364853
			],
			"coord_compensated_georef" : 
			[
				199.99999873507957,
				99.999997360072499,
				100.00006176388324
			],
			"coord_read" : 
			[
				200.0,
				100.0,
				100.0
			],
			"dev_eta" : null,
			"dev_xi" : null,
			"dimension" : 3,
			"ellips" : null,
			"file_id" : 0,
			"nbr_active_obs" : 15,
			"number" : 3,
			"params" : 
			{
				"s2_x" : 
				{
					"rank" : 19,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 199.99999867367913
				},
				"s2_y" : 
				{
					"rank" : 20,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 99.999997329372277
				},
				"s2_z" : 
				{
					"rank" : 21,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 100.00006176388324
				}
			},
			"shift_from_read" : 
			[
				-1.2649204279568949e-06,
				-2.6399275014910017e-06,
				6.1763883238086237e-05
			],
			"sigmas_init" : 
			[
				0.001,
				0.001,
				0.001
			],
			"stations" : 
			[
				{
					"nbr_active_obs" : 8,
					"num" : 1,
					"observations" : 
					[
						{
							"active" : true,
							"active_read" : true,
							"code" : -1,
							"comment" : "",
							"computed_value" : 199.99999867367913,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "s2",
							"instrument_height" : 0.0,
							"line" : 4,
							"normalized_residual" : -0.0012649204279568949,
							"number" : 9,
							"obs_azim" : 3.5751893614029748e-05,
							"obs_length" : 0.0,
							"obs_zen" : 0.0,
							"original_value" : 199.99999993859956,
							"rank" : 14,
							"residual" : -1.2649204279568949e-06,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "s2",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : -2,
							"comment" : "",
							"computed_value" : 99.999997329372277,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "s2",
							"instrument_height" : 0.0,
							"line" : 4,
							"normalized_residual" : -0.0026399275014910017,
							"number" : 10,
							"obs_azim" : 3.5751893614029748e-05,
							"obs_length" : 0.0,
							"obs_zen" : 0.0,
							"original_value" : 99.999999969299779,
							"rank" : 15,
							"residual" : -2.6399275014910017e-06,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "s2",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : -3,
							"comment" : "",
							"computed_value" : 100.0000617634505,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "s2",
							"instrument_height" : 0.0,
							"line" : 4,
							"normalized_residual" : 0.061763450503349304,
							"number" : 11,
							"obs_azim" : 3.5751893614029748e-05,
							"obs_length" : 0.0,
							"obs_zen" : 0.0,
							"original_value" : 100.0,
							"rank" : 16,
							"residual" : 6.1763450503349304e-05,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "s2",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 6,
							"comment" : "",
							"computed_value" : 100.0005157122288,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "s2",
							"instrument_height" : 0.0,
							"line" : 15,
							"normalized_residual" : 0.11571222880730643,
							"number" : 25,
							"obs_azim" : 3.141628379820339,
							"obs_length" : 100.00156449636468,
							"obs_zen" : 1.5708044275836437,
							"original_value" : 100.0004,
							"rank" : 17,
							"residual" : 0.00011571222880730643,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "o2",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 6,
							"comment" : "",
							"computed_value" : 121.87330225524791,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "s2",
							"instrument_height" : 0.0,
							"line" : 17,
							"normalized_residual" : 0.0022552478951425349,
							"number" : 27,
							"obs_azim" : -2.6779097043363351,
							"obs_length" : 118.74484313044131,
							"obs_zen" : 1.914381355169076,
							"original_value" : 121.8733,
							"rank" : 18,
							"residual" : 2.2552478951425351e-06,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "1",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 6,
							"comment" : "",
							"computed_value" : 83.11699877850306,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "s2",
							"instrument_height" : 0.0,
							"line" : 19,
							"normalized_residual" : -0.0012214969446739709,
							"number" : 29,
							"obs_azim" : -1.6614206671793199,
							"obs_length" : 114.45720040594676,
							"obs_zen" : 1.3055987637548851,
							"original_value" : 83.117000000000004,
							"rank" : 19,
							"residual" : -1.2214969446739708e-06,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "2",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 6,
							"comment" : "",
							"computed_value" : 90.579673660247977,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "s2",
							"instrument_height" : 0.0,
							"line" : 23,
							"normalized_residual" : -0.026339752031456869,
							"number" : 33,
							"obs_azim" : -1.1071134583652202,
							"obs_length" : 67.824457626450226,
							"obs_zen" : 1.4228221866779798,
							"original_value" : 90.579700000000003,
							"rank" : 20,
							"residual" : -2.6339752031456869e-05,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "4",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 6,
							"comment" : "",
							"computed_value" : 90.017537755006231,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "s2",
							"instrument_height" : 0.0,
							"line" : 25,
							"normalized_residual" : 0.037755006244088445,
							"number" : 35,
							"obs_azim" : -0.32171519822252009,
							"obs_length" : 128.06466308064969,
							"obs_zen" : 1.4139921765268473,
							"original_value" : 90.017499999999998,
							"rank" : 21,
							"residual" : 3.7755006244088451e-05,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "5",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						}
					],
					"params" : null,
					"type" : "simple"
				},
				{
					"nbr_active_obs" : 5,
					"num" : 1,
					"observations" : 
					[
						{
							"active" : true,
							"active_read" : true,
							"code" : 7,
							"comment" : "",
							"computed_value" : 200.00000127100432,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "s2",
							"instrument_height" : 0.0,
							"line" : 14,
							"normalized_residual" : 0.0015887553392981884,
							"number" : 24,
							"obs_azim" : 3.141628379820339,
							"obs_length" : 100.00156449636468,
							"obs_zen" : 1.5708044275836437,
							"original_value" : 200.0,
							"rank" : 27,
							"residual" : 1.2710042714385508e-06,
							"sigma_abs" : 0.00080000000000000004,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.00080000000000000004,
							"target_height" : 0.0,
							"to" : "o2",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : -170.48329977102492,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "s2",
							"instrument_height" : 0.0,
							"line" : 16,
							"normalized_residual" : 0.00028621889325382397,
							"number" : 26,
							"obs_azim" : -2.6779097043363351,
							"obs_length" : 118.74484313044131,
							"obs_zen" : 1.914381355169076,
							"original_value" : -170.48330000000001,
							"rank" : 28,
							"residual" : 2.2897511460305918e-07,
							"sigma_abs" : 0.00080000000000000004,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.00080000000000000004,
							"target_height" : 0.0,
							"to" : "1",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : -105.77159782612082,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "s2",
							"instrument_height" : 0.0,
							"line" : 18,
							"normalized_residual" : 0.002717349016788136,
							"number" : 28,
							"obs_azim" : -1.6614206671793199,
							"obs_length" : 114.45720040594676,
							"obs_zen" : 1.3055987637548851,
							"original_value" : -105.77160000000001,
							"rank" : 29,
							"residual" : 2.1738792134305091e-06,
							"sigma_abs" : 0.00080000000000000004,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.00080000000000000004,
							"target_height" : 0.0,
							"to" : "2",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : -70.483304916426675,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "s2",
							"instrument_height" : 0.0,
							"line" : 22,
							"normalized_residual" : -0.0061455333456292369,
							"number" : 32,
							"obs_azim" : -1.1071134583652202,
							"obs_length" : 67.824457626450226,
							"obs_zen" : 1.4228221866779798,
							"original_value" : -70.4833,
							"rank" : 30,
							"residual" : -4.9164266765033898e-06,
							"sigma_abs" : 0.00080000000000000004,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.00080000000000000004,
							"target_height" : 0.0,
							"to" : "4",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 5,
							"comment" : "",
							"computed_value" : -20.48329875743266,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "s2",
							"instrument_height" : 0.0,
							"line" : 24,
							"normalized_residual" : 0.0015532091774621804,
							"number" : 34,
							"obs_azim" : -0.32171519822252009,
							"obs_length" : 128.06466308064969,
							"obs_zen" : 1.4139921765268473,
							"original_value" : -20.4833,
							"rank" : 31,
							"residual" : 1.2425673419697445e-06,
							"sigma_abs" : 0.00080000000000000004,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.00080000000000000004,
							"target_height" : 0.0,
							"to" : "5",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						}
					],
					"params" : 
					{
						"s2_G0_1" : 
						{
							"rank" : 22,
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"value" : 3.5706265656839578e-05
						}
					},
					"type" : "hz_unknown"
				}
			]
		}
	}
}
