data=
{
	"COMP3D_COMMIT" : "v5.21rc3-273-ge3e3bf62-dirty",
	"COMP3D_COPYRIGHT" : "Copyright 1992-2022 IGN France",
	"COMP3D_LICENSE" : "Licensed to IGN/ENSG only",
	"COMP3D_OPTIONS" : "QT SIM ",
	"COMP3D_VERSION" : "COMP3D v5.22dev-linux",
	"all_data_files" : 
	{
		"0" : "coord.cor",
		"1" : "obs.obs"
	},
	"all_forbidden_point_names" : null,
	"all_point_names" : 
	[
		"A",
		"B"
	],
	"all_uninitializable_point_names" : null,
	"computation" : 
	{
		"Monte_Carlo_done" : false,
		"all_parameters_names" : 
		[
			"A_x",
			"A_y",
			"A_z",
			"B_x",
			"B_y",
			"B_z"
		],
		"all_sigma0" : 
		[
			0.20000000000000001,
			0.19999000174969209,
			0.19999000174969395
		],
		"biggest_ellips" : 0.019999686699285618,
		"chi2_test" : 
		{
			"DOF" : 1,
			"confidence" : 0.98999999999999999,
			"max" : 159.57586772460573,
			"min" : 0.35624794089670553
		},
		"compensation_done" : true,
		"computation_duration" : "00:00:00.000815",
		"computation_start" : "2023-May-15 14:52:32.618756",
		"internal_constraints" : false,
		"internal_constraints_obs" : [],
		"interrupted" : false,
		"inverted_matrix" : true,
		"kernel" : null,
		"messages_computation" : "",
		"messages_read_config" : "",
		"messages_read_data" : "Reading COR...<br/>\nRead file coord.cor...<br/>\nReading OBS...<br/>\nRead file obs.obs...<br/>\nReading coordinates covariance CSV file...<br/>\nPoints setting...<br/>\nRead data finished.<br/>\nAll points are initialized.<br/>\nVertical deflection not used.<br/>\n",
		"messages_set_least_squares" : "",
		"nbr_active_obs" : 7,
		"nbr_all_obs" : 7,
		"nbr_iterations" : 2,
		"nbr_parameters" : 6,
		"projection" : 
		{
			"center_latitude" : 48.79999999999999,
			"earth_model_radius" : 6380935.2757568145,
			"geocent_def" : "+proj=geocent",
			"input_proj_EPSG" : -1,
			"input_proj_def" : "+proj=sterea +lat_0=48.8 +lon_0=0 +k_0=1 +x_0=0 +y_0=0",
			"input_proj_name" : "?",
			"is_georef" : false,
			"latlong_def" : "+proj=latlong",
			"local_center_stereo" : 
			[
				0.0,
				0.0,
				0.0
			],
			"local_scale" : 1.0,
			"stereo_def" : "+proj=sterea +lat_0=48.8 +lon_0=0 +k_0=1 +x_0=0 +y_0=0"
		},
		"rank_deficiency" : 0,
		"sigma_0_final" : 0.19999000174969395,
		"sigma_0_init" : 0.20000000000000001,
		"unit_name" : "g",
		"use_vertical_deflection" : false
	},
	"config" : 
	{
		"center_latitude" : 48.799999999999997,
		"clean_outputs" : false,
		"compute_type" : 0,
		"convergence_criterion" : 0.001,
		"coord_cov_file" : "corcov.csv",
		"description" : "",
		"display_map" : true,
		"files_unit" : 1,
		"force_iterations" : 0,
		"internal_constraints" : false,
		"invert_matrix" : true,
		"lang" : "en",
		"local_center" : 
		[
			0.0,
			0.0,
			0.0
		],
		"max_iterations" : 100,
		"misc_metadata" : null,
		"name" : "corcov",
		"nb_digits" : 4,
		"proj_def" : "",
		"refraction" : 0.12,
		"root_COR_file" : "coord.cor",
		"root_OBS_file" : "obs.obs",
		"use_ellips_height" : true,
		"use_proj" : false
	},
	"config_file" : "/home/JMMuller/prog/comp3d_cpp/tests/data/corcov/ex_ref.comp_test.comp",
	"other_stations" : null,
	"points" : 
	{
		"A" : 
		{
			"code" : 1,
			"code_name" : "3xyz",
			"comment" : " overwritten by cov",
			"coord_compensated_cartesian" : 
			[
				100.00156486978163,
				100.00156944961078,
				99.998432806372932
			],
			"coord_compensated_georef" : 
			[
				100.0,
				100.0,
				100.0
			],
			"coord_read" : 
			[
				100.0,
				100.0,
				100.0
			],
			"dev_eta" : null,
			"dev_xi" : null,
			"dimension" : 3,
			"ellips" : 
			{
				"axes" : 
				[
					[
						0.00019999000174969394,
						100.0,
						99.999958519481183
					],
					[
						0.00019999000174967513,
						100.0,
						0.0
					],
					[
						0.0001999900017496712,
						136.18395162275158,
						0.0
					]
				],
				"matrix" : 
				[
					9.9999999999981191e-07,
					6.1669432265796812e-20,
					-1.225265963242475e-25,
					9.9999999999977253e-07,
					-2.3427854895046045e-29,
					9.9999999999999995e-07
				],
				"sigmas" : 
				[
					0.00019999000174967513,
					0.0001999900017496712,
					0.00019999000174969394
				]
			},
			"file_id" : 0,
			"nbr_active_obs" : 4,
			"number" : 0,
			"params" : 
			{
				"A_x" : 
				{
					"rank" : 0,
					"sigma" : 0.00019999000174967513,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 99.999999987719917
				},
				"A_y" : 
				{
					"rank" : 1,
					"sigma" : 0.0001999900017496712,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 99.999999987719917
				},
				"A_z" : 
				{
					"rank" : 2,
					"sigma" : 0.00019999000174969394,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 100.0
				}
			},
			"shift_from_read" : 
			[
				0.0,
				0.0,
				0.0
			],
			"sigmas_init" : 
			[
				0.001,
				0.001,
				0.001
			],
			"stations" : 
			[
				{
					"nbr_active_obs" : 4,
					"num" : 1,
					"observations" : 
					[
						{
							"active" : true,
							"active_read" : true,
							"code" : -1,
							"comment" : " overwritten by cov",
							"computed_value" : 99.999999987719917,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "A",
							"instrument_height" : 0.0,
							"line" : 1,
							"normalized_residual" : 0.0,
							"number" : 0,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_redondancy" : 1.8829382497642655e-11,
							"obs_zen" : 0.0,
							"original_value" : 99.999999987719917,
							"rank" : 0,
							"residual" : 0.0,
							"residual_std" : 0.0,
							"sigma_a_posteriori" : 0.00099999999999990591,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "A",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : true
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : -2,
							"comment" : " overwritten by cov",
							"computed_value" : 99.999999987719917,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "A",
							"instrument_height" : 0.0,
							"line" : 1,
							"normalized_residual" : 0.0,
							"number" : 1,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_redondancy" : 2.2759572004815709e-11,
							"obs_zen" : 0.0,
							"original_value" : 99.999999987719917,
							"rank" : 1,
							"residual" : 0.0,
							"residual_std" : 0.0,
							"sigma_a_posteriori" : 0.00099999999999988618,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "A",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : true
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : -3,
							"comment" : " overwritten by cov",
							"computed_value" : 100.0,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "A",
							"instrument_height" : 0.0,
							"line" : 1,
							"normalized_residual" : 0.0,
							"number" : 2,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_redondancy" : 0.0,
							"obs_zen" : 0.0,
							"original_value" : 100.0,
							"rank" : 2,
							"residual" : 0.0,
							"residual_std" : 0.0,
							"sigma_a_posteriori" : 0.001,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "A",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : true
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 4,
							"comment" : "just for redondancy",
							"computed_value" : 1.9995495676994324e-05,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "A",
							"instrument_height" : 0.0,
							"line" : 1,
							"nabla" : 4.1002049743783298,
							"normalized_residual" : -0.19998000450432302,
							"number" : 6,
							"obs_azim" : 1.0471848488998781,
							"obs_length" : 9.9999367071918766,
							"obs_redondancy" : 99.990001999600082,
							"obs_zen" : 1.5707950167266633,
							"original_value" : 0.20000000000000001,
							"rank" : 3,
							"residual" : -0.19998000450432302,
							"residual_std" : -20.000000150487342,
							"sigma_a_posteriori" : 0.0099990001499800033,
							"sigma_abs" : 1.0,
							"sigma_rel" : 0.0,
							"sigma_residual" : 0.99995000874843776,
							"sigma_total" : 1.0,
							"standardized_residual" : -0.19999000225483568,
							"target_height" : 0.0,
							"to" : "B",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						}
					],
					"params" : null,
					"type" : "simple"
				}
			]
		},
		"B" : 
		{
			"code" : 1,
			"code_name" : "3xyz",
			"comment" : " overwritten by cov",
			"coord_compensated_cartesian" : 
			[
				108.66170038592233,
				105.00164791997952,
				99.998230976864377
			],
			"coord_compensated_georef" : 
			[
				108.65999999996914,
				104.99999999998219,
				100.0000199955746
			],
			"coord_read" : 
			[
				108.66,
				105.0,
				100.0
			],
			"dev_eta" : null,
			"dev_xi" : null,
			"dimension" : 3,
			"ellips" : 
			{
				"axes" : 
				[
					[
						0.019999686699285618,
						66.666600012006697,
						1.1567938420093449e-06
					],
					[
						0.0020096756755068677,
						66.66660000300763,
						99.999999051362622
					],
					[
						0.00020001467210888356,
						166.66660001200421,
						200.0
					]
				],
				"matrix" : 
				[
					0.0075007559224147258,
					0.0043299964279674853,
					-1.5578603941895926e-10,
					0.0025009308947386275,
					-8.9943329273526829e-11,
					0.00010098000399930012
				],
				"sigmas" : 
				[
					0.017320515000204914,
					0.010001361610616684,
					0.0020096756755068998
				]
			},
			"file_id" : 0,
			"nbr_active_obs" : 4,
			"number" : 1,
			"params" : 
			{
				"B_x" : 
				{
					"rank" : 3,
					"sigma" : 0.017320515000204914,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 108.65999998473613
				},
				"B_y" : 
				{
					"rank" : 4,
					"sigma" : 0.010001361610616684,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 104.99999998526228
				},
				"B_z" : 
				{
					"rank" : 5,
					"sigma" : 0.0020096756755068998,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 100.0000199955746
				}
			},
			"shift_from_read" : 
			[
				-3.085176558670355e-11,
				-1.7806200958148111e-11,
				1.9995574604081412e-05
			],
			"sigmas_init" : 
			[
				0.086606904588606565,
				0.050009308080996281,
				0.010049378139964682
			],
			"stations" : 
			[
				{
					"nbr_active_obs" : 3,
					"num" : 1,
					"observations" : 
					[
						{
							"active" : true,
							"active_read" : true,
							"code" : -1,
							"comment" : " overwritten by cov",
							"computed_value" : 108.65999998473613,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "B",
							"instrument_height" : 0.0,
							"line" : 2,
							"normalized_residual" : -3.5655572084949388e-10,
							"number" : 3,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_redondancy" : 7.0321526379757415e-11,
							"obs_zen" : 0.0,
							"original_value" : 108.65999998476701,
							"rank" : 4,
							"residual" : -3.0880187296133954e-11,
							"residual_std" : -3.5655572084961925e-10,
							"sigma_a_posteriori" : 0.086606904588576117,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.086606904588606565,
							"target_height" : 0.0,
							"to" : "B",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : true
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : -2,
							"comment" : " overwritten by cov",
							"computed_value" : 104.99999998526228,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "B",
							"instrument_height" : 0.0,
							"line" : 2,
							"normalized_residual" : -3.5662606326592502e-10,
							"number" : 4,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_redondancy" : 5.4889426337467739e-11,
							"obs_zen" : 0.0,
							"original_value" : 104.99999998528011,
							"rank" : 5,
							"residual" : -1.7834622667578515e-11,
							"residual_std" : -3.5662606326602288e-10,
							"sigma_a_posteriori" : 0.050009308080982556,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.050009308080996281,
							"target_height" : 0.0,
							"to" : "B",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : true
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : -3,
							"comment" : " overwritten by cov",
							"computed_value" : 100.00001999549568,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "B",
							"instrument_height" : 0.0,
							"line" : 2,
							"normalized_residual" : 0.001989724677338552,
							"number" : 5,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_redondancy" : 0.0098990004959942368,
							"obs_zen" : 0.0,
							"original_value" : 100.0,
							"rank" : 6,
							"residual" : 1.9995495676994324e-05,
							"residual_std" : 0.0019898231660785025,
							"sigma_a_posteriori" : 0.010048880733658854,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.010049378139964682,
							"target_height" : 0.0,
							"to" : "B",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : true
						}
					],
					"params" : null,
					"type" : "simple"
				}
			]
		}
	}
}
