FROM ubuntu:16.04

RUN apt-get update && apt-get install -y --fix-missing \
wget unzip libboost-all-dev qttools5-dev-tools qt5-default libeigen3-dev git \
doxygen sqlite libsqlite3-dev fuse
    
#get proj
RUN cd / && \
    wget https://download.osgeo.org/proj/proj-6.1.1.tar.gz  && \
    tar -xf proj-6.1.1.tar.gz  && \
    cd proj-6.1.1  && \
    ./configure --prefix=/usr/local/proj61/  && \
    make clean  && \
    make -j5  && \
    make install  && \
    cp /usr/local/proj61/lib/libproj.so.15 /usr/lib/

#get proj data
RUN cd / && \
    wget https://download.osgeo.org/proj/proj-datumgrid-1.8.zip && \
    unzip proj-datumgrid-1.8.zip -d proj-data && \
    mkdir -p /usr/local/proj61/share/proj/ && \
    cp proj-data/* /usr/local/proj61/share/proj/

#add AppImage tools
RUN mkdir -p /AppImageTools/ && cd /AppImageTools/ && \
      wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage && \
      wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage && \
      chmod a+x *.AppImage

#add mxe for win cross compilation
RUN apt-get install -y --fix-missing \
    autoconf automake autopoint bash bison bzip2 flex g++ g++-multilib gettext git gperf intltool libc6-dev-i386 \
    libgdk-pixbuf2.0-dev libltdl-dev libssl-dev libtool-bin libxml-parser-perl lzip make openssl p7zip-full \
    patch perl python ruby sed unzip wget xz-utils python3

#compile mxe
RUN cd / && \
    git clone --branch build-2020-06-06 https://github.com/mxe/mxe.git && \
    cd mxe && \
    git checkout -b tmp && \
    make boost  && \
    make eigen  && \
    make sqlite && \
    make qt5

#proj for mxe
RUN cd /proj-6.1.1  && \
    ./configure --host=i686-w64-mingw32.static --enable-static --disable-shared --prefix=/mxe/usr/i686-w64-mingw32.static/ && \
    make clean  && \
    make -j5  && \
    make install

