data=
{
	"COMP3D_COMMIT" : "v5.21rc3-273-ge3e3bf62-dirty",
	"COMP3D_COPYRIGHT" : "Copyright 1992-2022 IGN France",
	"COMP3D_LICENSE" : "Licensed to IGN/ENSG only",
	"COMP3D_OPTIONS" : "QT SIM ",
	"COMP3D_VERSION" : "COMP3D v5.22dev-linux",
	"all_data_files" : 
	{
		"0" : "coord.cor",
		"1" : "obs.obs"
	},
	"all_forbidden_point_names" : null,
	"all_point_names" : 
	[
		"a",
		"b"
	],
	"all_uninitializable_point_names" : null,
	"computation" : 
	{
		"Monte_Carlo_done" : true,
		"all_parameters_names" : 
		[
			"a_x",
			"a_y",
			"a_z",
			"b_x",
			"b_y",
			"b_z"
		],
		"all_sigma0" : 
		[
			0.74919943200937666,
			1.2694379801815405,
			1.1711542072053891,
			1.2702363582702529,
			0.61698310634216191,
			0.40173508866738239,
			0.86972724965592862,
			0.82780982519428248,
			1.5913212552874108,
			1.4360353732907944,
			0.53736262426694748,
			0.95611938157262888,
			0.93324579850894118,
			1.6183261240768736,
			1.1964521178022383,
			0.80455146947849154,
			0.47505026837779823,
			1.0875889553318334,
			0.94111369335353345,
			1.0273072582793263,
			0.75715608832929071
		],
		"chi2_test" : 
		{
			"DOF" : 1,
			"confidence" : 0.98999999999999999,
			"max" : 159.57586772460573,
			"min" : 0.35624794089670553
		},
		"compensation_done" : false,
		"computation_duration" : "00:00:00.006610",
		"computation_start" : "2023-May-15 14:52:28.448102",
		"internal_constraints" : false,
		"internal_constraints_obs" : [],
		"interrupted" : false,
		"inverted_matrix" : false,
		"kernel" : null,
		"messages_computation" : "",
		"messages_read_config" : "",
		"messages_read_data" : "Reading COR...<br/>\nRead file coord.cor...<br/>\nReading OBS...<br/>\nRead file obs.obs...<br/>\nPoints setting...<br/>\nRead data finished.<br/>\nVertical deflection not used.<br/>\n",
		"messages_set_least_squares" : "",
		"nbr_active_obs" : 7,
		"nbr_all_obs" : 8,
		"nbr_iterations" : 20,
		"nbr_parameters" : 6,
		"projection" : 
		{
			"center_latitude" : 48.79999999999999,
			"earth_model_radius" : 6380935.2757568145,
			"geocent_def" : "+proj=geocent",
			"input_proj_EPSG" : -1,
			"input_proj_def" : "+proj=sterea +lat_0=48.8 +lon_0=0 +k_0=1 +x_0=0 +y_0=0",
			"input_proj_name" : "?",
			"is_georef" : false,
			"latlong_def" : "+proj=latlong",
			"local_center_stereo" : 
			[
				0.0,
				0.0,
				0.0
			],
			"local_scale" : 1.0,
			"stereo_def" : "+proj=sterea +lat_0=48.8 +lon_0=0 +k_0=1 +x_0=0 +y_0=0"
		},
		"rank_deficiency" : 0,
		"unit_name" : "g",
		"use_vertical_deflection" : false
	},
	"config" : 
	{
		"center_latitude" : 48.799999999999997,
		"clean_outputs" : false,
		"compute_type" : 2,
		"convergence_criterion" : 0.001,
		"coord_cov_file" : "",
		"description" : "",
		"display_map" : true,
		"files_unit" : 1,
		"force_iterations" : 0,
		"internal_constraints" : false,
		"invert_matrix" : false,
		"lang" : "en",
		"local_center" : 
		[
			0.0,
			0.0,
			0.0
		],
		"max_iterations" : 20,
		"misc_metadata" : null,
		"name" : "simul_mini",
		"nb_digits" : 6,
		"proj_def" : "?",
		"refraction" : 0.12,
		"root_COR_file" : "coord.cor",
		"root_OBS_file" : "obs.obs",
		"use_ellips_height" : true,
		"use_proj" : false
	},
	"config_file" : "/home/JMMuller/prog/comp3d_cpp/tests/data/simulMCmini/ex_ref.comp_test.comp",
	"other_stations" : null,
	"points" : 
	{
		"a" : 
		{
			"MC_shift_max" : 
			[
				0.0019424711513231459,
				0.0016221838829666494,
				0.0016019573489158339
			],
			"MC_shift_sq_average" : 
			[
				0.00081352869656575136,
				0.00097698488004195464,
				0.00069054381619632608
			],
			"code" : 1,
			"code_name" : "3xyz",
			"comment" : "",
			"coord_compensated_cartesian" : 
			[
				0.0,
				0.0,
				0.0
			],
			"coord_read" : 
			[
				0.0,
				0.0,
				0.0
			],
			"dev_eta" : null,
			"dev_xi" : null,
			"dimension" : 3,
			"ellips" : null,
			"file_id" : 0,
			"nbr_active_obs" : 6,
			"number" : 0,
			"params" : 
			{
				"a_x" : 
				{
					"rank" : 0,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 0.0
				},
				"a_y" : 
				{
					"rank" : 1,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 0.0
				},
				"a_z" : 
				{
					"rank" : 2,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 0.0
				}
			},
			"sigmas_init" : 
			[
				0.001,
				0.001,
				0.001
			],
			"stations" : 
			[
				{
					"nbr_active_obs" : 6,
					"num" : 1,
					"observations" : 
					[
						{
							"active" : true,
							"active_read" : true,
							"code" : -1,
							"comment" : "",
							"computed_value" : 0.0,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "a",
							"instrument_height" : 0.0,
							"line" : 1,
							"normalized_residual" : 0.0,
							"number" : 0,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_zen" : 0.0,
							"original_value" : 0.0,
							"rank" : 0,
							"residual" : 0.00020374735657867915,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "a",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : -2,
							"comment" : "",
							"computed_value" : 0.0,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "a",
							"instrument_height" : 0.0,
							"line" : 1,
							"normalized_residual" : 0.0,
							"number" : 1,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_zen" : 0.0,
							"original_value" : 0.0,
							"rank" : 1,
							"residual" : -0.0012757713813374518,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "a",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : -3,
							"comment" : "",
							"computed_value" : 0.0,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "a",
							"instrument_height" : 0.0,
							"line" : 1,
							"normalized_residual" : 0.0,
							"number" : 2,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_zen" : 0.0,
							"original_value" : 0.0,
							"rank" : 2,
							"residual" : 0.0017330718389074384,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "a",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 8,
							"comment" : "",
							"computed_value" : 0.0,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "a",
							"instrument_height" : 0.0,
							"line" : 1,
							"normalized_residual" : 0.0,
							"number" : 4,
							"obs_azim" : 1.5707963267948966,
							"obs_length" : 9.9999999999928395,
							"obs_zen" : 1.5707970163549321,
							"original_value" : 100.0,
							"rank" : 3,
							"residual" : 0.00028966979941667098,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "b",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 6,
							"comment" : "",
							"computed_value" : 0.0,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "a",
							"instrument_height" : 0.0,
							"line" : 2,
							"normalized_residual" : 0.0,
							"number" : 5,
							"obs_azim" : 1.5707963267948966,
							"obs_length" : 9.9999999999928395,
							"obs_zen" : 1.5707970163549321,
							"original_value" : 100.0,
							"rank" : 4,
							"residual" : 0.00042457277314665337,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "b",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 3,
							"comment" : "",
							"computed_value" : 0.0,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "a",
							"instrument_height" : 0.0,
							"line" : 3,
							"normalized_residual" : 0.0,
							"number" : 6,
							"obs_azim" : 1.5707963267948966,
							"obs_length" : 9.9999999999928395,
							"obs_zen" : 1.5707970163549321,
							"original_value" : 10.0,
							"rank" : 5,
							"residual" : 0.00063555063833250136,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "b",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						},
						{
							"active" : false,
							"active_read" : false,
							"code" : 4,
							"comment" : "",
							"computed_value" : 0.0,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "a",
							"instrument_height" : 0.0,
							"line" : 6,
							"normalized_residual" : 0.0,
							"number" : 7,
							"obs_azim" : 1.5707963267948966,
							"obs_length" : 9.9999999999928395,
							"obs_zen" : 1.5707970163549321,
							"original_value" : 0.0,
							"rank" : -1,
							"residual" : 0.00090122291354566275,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "b",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						}
					],
					"params" : null,
					"type" : "simple"
				}
			]
		},
		"b" : 
		{
			"MC_shift_max" : 
			[
				0.0022311771244734047,
				0.0018273638317143142,
				0.0016707544816479869
			],
			"MC_shift_sq_average" : 
			[
				0.0011829551139908561,
				0.00098294507460414148,
				0.00069397296696076564
			],
			"code" : 3,
			"code_name" : "3--z",
			"comment" : "",
			"coord_compensated_cartesian" : 
			[
				9.9999999999938769,
				-4.3249362161212375e-10,
				-7.8236157279149937e-06
			],
			"coord_read" : 
			[
				10.0,
				0.0,
				0.0
			],
			"dev_eta" : null,
			"dev_xi" : null,
			"dimension" : 3,
			"ellips" : null,
			"file_id" : 0,
			"nbr_active_obs" : 4,
			"number" : 1,
			"params" : 
			{
				"b_x" : 
				{
					"rank" : 3,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 9.9999999999938609
				},
				"b_y" : 
				{
					"rank" : 4,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 0.0
				},
				"b_z" : 
				{
					"rank" : 5,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 0.0
				}
			},
			"sigmas_init" : 
			[
				0.001,
				0.001,
				0.001
			],
			"stations" : 
			[
				{
					"nbr_active_obs" : 1,
					"num" : 1,
					"observations" : 
					[
						{
							"active" : true,
							"active_read" : true,
							"code" : -3,
							"comment" : "",
							"computed_value" : 0.0,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "b",
							"instrument_height" : 0.0,
							"line" : 2,
							"normalized_residual" : 0.0,
							"number" : 3,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_zen" : 0.0,
							"original_value" : 0.0,
							"rank" : 6,
							"residual" : 7.5652248230675259e-05,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "b",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						}
					],
					"params" : null,
					"type" : "simple"
				}
			]
		}
	}
}
