data=
{
	"COMP3D_COMMIT" : "v5.21rc3-330-g8688f99f",
	"COMP3D_COPYRIGHT" : "Copyright 1992-2023 IGN France",
	"COMP3D_LICENSE" : "Licensed to IGN/ENSG only",
	"COMP3D_OPTIONS" : "QT SIM ",
	"COMP3D_VERSION" : "COMP3D v5.22dev-linux",
	"all_data_files" : 
	{
		"0" : "coord.cor",
		"1" : "obs.obs"
	},
	"all_forbidden_point_names" : null,
	"all_point_names" : 
	[
		"a",
		"b"
	],
	"all_uninitializable_point_names" : null,
	"computation" : 
	{
		"Monte_Carlo_done" : false,
		"all_parameters_names" : 
		[
			"a_x",
			"a_y",
			"a_z",
			"b_x",
			"b_y",
			"b_z"
		],
		"all_sigma0" : 
		[
			1.0
		],
		"biggest_ellips" : 0.00050000000559431463,
		"chi2_test" : 
		{
			"DOF" : 0,
			"confidence" : 0.98999999999999999,
			"max" : null,
			"min" : null
		},
		"compensation_done" : false,
		"computation_duration" : "00:00:00.000302",
		"computation_start" : "2023-Aug-17 16:16:09.562330",
		"internal_constraints" : true,
		"internal_constraints_obs" : 
		[
			{
				"active" : true,
				"active_read" : true,
				"code" : 203,
				"comment" : "",
				"computed_value" : 0.0,
				"deflection_correction" : 0.0,
				"file_id" : -1,
				"from" : "?",
				"instrument_height" : 0.0,
				"line" : 0,
				"normalized_residual" : 0.0,
				"number" : 8,
				"obs_azim" : 0.0,
				"obs_length" : 0.0,
				"obs_redondancy" : 4.0633274522861029e-09,
				"obs_zen" : 0.0,
				"original_value" : 0.0,
				"rank" : 2,
				"residual" : 0.0,
				"residual_std" : 0.0,
				"sigma_a_posteriori" : 9.9999999997968334e-08,
				"sigma_abs" : 9.9999999999999995e-08,
				"sigma_rel" : 0.0,
				"sigma_total" : 9.9999999999999995e-08,
				"target_height" : 0.0,
				"to" : "?",
				"unit_factor" : 1.0,
				"unit_str" : "",
				"variance_from_matrix" : false
			},
			{
				"active" : true,
				"active_read" : true,
				"code" : 201,
				"comment" : "",
				"computed_value" : 0.0,
				"deflection_correction" : 0.0,
				"file_id" : -1,
				"from" : "?",
				"instrument_height" : 0.0,
				"line" : 0,
				"normalized_residual" : 0.0,
				"number" : 9,
				"obs_azim" : 0.0,
				"obs_length" : 0.0,
				"obs_redondancy" : 1.6365790944661285e-07,
				"obs_zen" : 0.0,
				"original_value" : 0.0,
				"rank" : 3,
				"residual" : 0.0,
				"residual_std" : 0.0,
				"sigma_a_posteriori" : 9.9999999918171041e-08,
				"sigma_abs" : 9.9999999999999995e-08,
				"sigma_rel" : 0.0,
				"sigma_total" : 9.9999999999999995e-08,
				"target_height" : 0.0,
				"to" : "?",
				"unit_factor" : 1.0,
				"unit_str" : "",
				"variance_from_matrix" : false
			},
			{
				"active" : true,
				"active_read" : true,
				"code" : 202,
				"comment" : "",
				"computed_value" : 0.0,
				"deflection_correction" : 0.0,
				"file_id" : -1,
				"from" : "?",
				"instrument_height" : 0.0,
				"line" : 0,
				"normalized_residual" : 0.0,
				"number" : 10,
				"obs_azim" : 0.0,
				"obs_length" : 0.0,
				"obs_redondancy" : 0.0,
				"obs_zen" : 0.0,
				"original_value" : 0.0,
				"rank" : 4,
				"residual" : 0.0,
				"residual_std" : 0.0,
				"sigma_a_posteriori" : 9.9999999999999995e-08,
				"sigma_abs" : 9.9999999999999995e-08,
				"sigma_rel" : 0.0,
				"sigma_total" : 9.9999999999999995e-08,
				"target_height" : 0.0,
				"to" : "?",
				"unit_factor" : 1.0,
				"unit_str" : "",
				"variance_from_matrix" : false
			},
			{
				"active" : true,
				"active_read" : true,
				"code" : 206,
				"comment" : "",
				"computed_value" : 0.0,
				"deflection_correction" : 0.0,
				"file_id" : -1,
				"from" : "?",
				"instrument_height" : 0.0,
				"line" : 0,
				"normalized_residual" : 0.0,
				"number" : 11,
				"obs_azim" : 0.0,
				"obs_length" : 0.0,
				"obs_redondancy" : 0.0,
				"obs_zen" : 0.0,
				"original_value" : 0.0,
				"rank" : 5,
				"residual" : 0.0,
				"residual_std" : 0.0,
				"sigma_a_posteriori" : 9.9999999999999995e-08,
				"sigma_abs" : 9.9999999999999995e-08,
				"sigma_rel" : 0.0,
				"sigma_total" : 9.9999999999999995e-08,
				"target_height" : 0.0,
				"to" : "?",
				"unit_factor" : 1.0,
				"unit_str" : "",
				"variance_from_matrix" : false
			}
		],
		"interrupted" : false,
		"inverted_matrix" : true,
		"kernel" : null,
		"messages_computation" : "",
		"messages_read_config" : "",
		"messages_read_data" : "Reading COR...<br/>\nRead file coord.cor...<br/>\nReading OBS...<br/>\nRead file obs.obs...<br/>\nPoints setting...<br/>\nRead data finished.<br/>\nVertical deflection not used.<br/>\n",
		"messages_set_least_squares" : "",
		"nbr_active_obs" : 6,
		"nbr_all_obs" : 8,
		"nbr_iterations" : 0,
		"nbr_parameters" : 6,
		"projection" : 
		{
			"center_latitude" : 48.79999999999999,
			"earth_model_radius" : 6380935.2757568145,
			"geocent_def" : "+proj=geocent",
			"input_proj_EPSG" : -1,
			"input_proj_def" : "+proj=sterea +lat_0=48.8 +lon_0=0 +k_0=1 +x_0=0 +y_0=0",
			"input_proj_name" : "?",
			"is_georef" : false,
			"latlong_def" : "+proj=latlong",
			"local_center_stereo" : 
			[
				0.0,
				0.0,
				0.0
			],
			"local_scale" : 1.0,
			"stereo_def" : "+proj=sterea +lat_0=48.8 +lon_0=0 +k_0=1 +x_0=0 +y_0=0"
		},
		"rank_deficiency" : 0,
		"solver_name" : "N5Eigen8SparseQRINS_12SparseMatrixIdLi0EiEENS_15NaturalOrderingIiEEEE",
		"unit_name" : "g",
		"use_vertical_deflection" : false
	},
	"config" : 
	{
		"center_latitude" : 48.799999999999997,
		"clean_outputs" : false,
		"compute_type" : 1,
		"convergence_criterion" : 0.001,
		"coord_cov_file" : "",
		"description" : "",
		"display_map" : true,
		"files_unit" : 1,
		"force_iterations" : 0,
		"internal_constraints" : true,
		"invert_matrix" : true,
		"lang" : "en",
		"local_center" : 
		[
			0.0,
			0.0,
			0.0
		],
		"max_iterations" : 1000,
		"misc_metadata" : null,
		"name" : "simul_mini",
		"nb_digits" : 6,
		"proj_def" : "?",
		"refraction" : 0.12,
		"root_COR_file" : "coord.cor",
		"root_OBS_file" : "obs.obs",
		"use_ellips_height" : true,
		"use_proj" : false
	},
	"config_file" : "/home/JMMuller/prog/comp3d_cpp/tests/data/simul_IC_mini/ex_ref.comp_test.comp",
	"other_stations" : null,
	"points" : 
	{
		"a" : 
		{
			"code" : 1,
			"code_name" : "3xyz",
			"comment" : "",
			"coord_compensated_cartesian" : 
			[
				0.0,
				0.0,
				0.0
			],
			"coord_read" : 
			[
				0.0,
				0.0,
				0.0
			],
			"dev_eta" : null,
			"dev_xi" : null,
			"dimension" : 3,
			"ellips" : 
			{
				"axes" : 
				[
					[
						0.00050000000559431463,
						100.0,
						5.114850832406444e-05
					],
					[
						7.853984817292873e-05,
						100.0,
						100.00005113850654
					],
					[
						9.9999999999999995e-08,
						200.0,
						0.0
					]
				],
				"matrix" : 
				[
					2.500000055941572e-07,
					0.0,
					1.9590370796557809e-13,
					9.9999999999999984e-15,
					0.0,
					6.1685077511840908e-09
				],
				"sigmas" : 
				[
					0.0005000000055941572,
					9.9999999999999995e-08,
					7.8539848173930736e-05
				]
			},
			"file_id" : 0,
			"nbr_active_obs" : 2,
			"number" : 0,
			"params" : 
			{
				"a_x" : 
				{
					"rank" : 0,
					"sigma" : 0.0005000000055941572,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 0.0
				},
				"a_y" : 
				{
					"rank" : 1,
					"sigma" : 9.9999999999999995e-08,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 0.0
				},
				"a_z" : 
				{
					"rank" : 2,
					"sigma" : 7.8539848173930736e-05,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 0.0
				}
			},
			"sigmas_init" : 
			[
				0.001,
				0.001,
				0.001
			],
			"stations" : 
			[
				{
					"nbr_active_obs" : 2,
					"num" : 1,
					"observations" : 
					[
						{
							"active" : true,
							"active_read" : true,
							"code" : -1,
							"comment" : "",
							"computed_value" : 0.0,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "a",
							"instrument_height" : 0.0,
							"line" : 1,
							"normalized_residual" : 0.0,
							"number" : 0,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_zen" : 0.0,
							"original_value" : 0.0,
							"rank" : -1,
							"residual" : 0.0,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "a",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : -2,
							"comment" : "",
							"computed_value" : 0.0,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "a",
							"instrument_height" : 0.0,
							"line" : 1,
							"normalized_residual" : 0.0,
							"number" : 1,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_zen" : 0.0,
							"original_value" : 0.0,
							"rank" : -1,
							"residual" : 0.0,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "a",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : -3,
							"comment" : "",
							"computed_value" : 0.0,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "a",
							"instrument_height" : 0.0,
							"line" : 1,
							"normalized_residual" : 0.0,
							"number" : 2,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_zen" : 0.0,
							"original_value" : 0.0,
							"rank" : -1,
							"residual" : 0.0,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "a",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 8,
							"comment" : "",
							"computed_value" : 0.0,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "a",
							"instrument_height" : 0.0,
							"line" : 1,
							"normalized_residual" : 0.0,
							"number" : 4,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_zen" : 0.0,
							"original_value" : 100.0,
							"rank" : -1,
							"residual" : 0.0,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "b",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 6,
							"comment" : "",
							"computed_value" : 0.0,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "a",
							"instrument_height" : 0.0,
							"line" : 2,
							"normalized_residual" : 0.0,
							"number" : 5,
							"obs_azim" : 1.5707963267948966,
							"obs_length" : 9.9999999999928395,
							"obs_redondancy" : -5.7513993567681609e-09,
							"obs_zen" : 1.5707970163549321,
							"original_value" : 100.0,
							"rank" : 0,
							"residual" : 0.0,
							"residual_std" : 0.0,
							"sigma_a_posteriori" : 0.001000000000028757,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "b",
							"unit_factor" : 0.015707963267948967,
							"unit_str" : "g",
							"variance_from_matrix" : false
						},
						{
							"active" : true,
							"active_read" : true,
							"code" : 3,
							"comment" : "",
							"computed_value" : 0.0,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "a",
							"instrument_height" : 0.0,
							"line" : 3,
							"normalized_residual" : 0.0,
							"number" : 6,
							"obs_azim" : 1.5707963267948966,
							"obs_length" : 9.9999999999928395,
							"obs_redondancy" : -2.3768325085882225e-07,
							"obs_zen" : 1.5707970163549321,
							"original_value" : 10.0,
							"rank" : 1,
							"residual" : 0.0,
							"residual_std" : 0.0,
							"sigma_a_posteriori" : 0.0010000000011884164,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "b",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						},
						{
							"active" : false,
							"active_read" : false,
							"code" : 4,
							"comment" : "",
							"computed_value" : 0.0,
							"deflection_correction" : 0.0,
							"file_id" : 1,
							"from" : "a",
							"instrument_height" : 0.0,
							"line" : 6,
							"normalized_residual" : 0.0,
							"number" : 7,
							"obs_azim" : 1.5707963267948966,
							"obs_length" : 9.9999999999928395,
							"obs_zen" : 1.5707970163549321,
							"original_value" : 0.0,
							"rank" : -1,
							"residual" : 0.0,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "b",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						}
					],
					"params" : null,
					"type" : "simple"
				}
			]
		},
		"b" : 
		{
			"code" : 3,
			"code_name" : "3--z",
			"comment" : "",
			"coord_compensated_cartesian" : 
			[
				9.9999999999938769,
				-4.3249362161212375e-10,
				-7.8236157279149937e-06
			],
			"coord_read" : 
			[
				10.0,
				0.0,
				0.0
			],
			"dev_eta" : null,
			"dev_xi" : null,
			"dimension" : 3,
			"ellips" : 
			{
				"axes" : 
				[
					[
						0.00050000000559431463,
						100.0,
						5.1148506278124145e-05
					],
					[
						7.8539848172928743e-05,
						100.0,
						100.00005113850654
					],
					[
						9.9999999999999995e-08,
						200.0,
						0.0
					]
				],
				"matrix" : 
				[
					2.500000055941572e-07,
					0.0,
					1.9590370012942998e-13,
					9.9999999999999984e-15,
					0.0,
					6.1685077511840916e-09
				],
				"sigmas" : 
				[
					0.0005000000055941572,
					9.9999999999999995e-08,
					7.8539848173930736e-05
				]
			},
			"file_id" : 0,
			"nbr_active_obs" : 2,
			"number" : 1,
			"params" : 
			{
				"b_x" : 
				{
					"rank" : 3,
					"sigma" : 0.0005000000055941572,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 9.9999999999938609
				},
				"b_y" : 
				{
					"rank" : 4,
					"sigma" : 9.9999999999999995e-08,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 0.0
				},
				"b_z" : 
				{
					"rank" : 5,
					"sigma" : 7.8539848173930736e-05,
					"unit_factor" : 1.0,
					"unit_str" : "m",
					"value" : 0.0
				}
			},
			"sigmas_init" : 
			[
				0.001,
				0.001,
				0.001
			],
			"stations" : 
			[
				{
					"nbr_active_obs" : 0,
					"num" : 1,
					"observations" : 
					[
						{
							"active" : true,
							"active_read" : true,
							"code" : -3,
							"comment" : "",
							"computed_value" : 0.0,
							"deflection_correction" : 0.0,
							"file_id" : 0,
							"from" : "b",
							"instrument_height" : 0.0,
							"line" : 2,
							"normalized_residual" : 0.0,
							"number" : 3,
							"obs_azim" : 0.0,
							"obs_length" : 0.0,
							"obs_zen" : 0.0,
							"original_value" : 0.0,
							"rank" : -1,
							"residual" : 0.0,
							"sigma_abs" : 0.001,
							"sigma_rel" : 0.0,
							"sigma_total" : 0.001,
							"target_height" : 0.0,
							"to" : "b",
							"unit_factor" : 1.0,
							"unit_str" : "m",
							"variance_from_matrix" : false
						}
					],
					"params" : null,
					"type" : "simple"
				}
			]
		}
	}
}
